
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/kumar/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
...
